### ISSUE TITLE
Extension Doesn't Work

### ISSUE THREAD

**Issue by patrickdark** [callahad/quick-accept-language-switcher#4]
This extension doesn't appear to work at all in Firefox 52.0.1. Checking the `accept-language` header in the network tab indicates that nothing changed despite the button icon indicating a change.

The extension also doesn't clearly indicate what the required syntax is; does it use the full header syntax, a partial syntax excluding the `; q=` component or what?

**Comment by callahad** [comment]
Sorry for the delay, I found the bug (https://bugzil.la/1358496) and a simple workaround. Pushing a new version to AMO now.

**Comment by callahad** [comment]
The new version is in the queue, will close this bug once it's live.

**Comment by callahad** [comment]
Version 1.1 is now available on AMO: https://addons.mozilla.org/en-US/firefox/addon/quick-accept-language-switc/

**Comment by patrickdark** [comment]
Confirmed that it's working in Firefox 53.0. Thanks.
