### ISSUE TITLE
Extension Displays "en;q" et Cetera

### ISSUE THREAD

**Issue by patrickdark** [callahad/quick-accept-language-switcher#5]
If the header string is something like "en;q=1", then "en;q" is displayed over the icon. Not sure if this is intentional or not. (Edit: Seems unintentional since "eng;q=0" displays "eng;".)

If the header string is contains invalid values like "en;q", "en;x", or "en=x", then "en;q", "en;x", and "en=" are displayed respectively. Seem like bugs.

**Comment by callahad** [comment]
Let's call this a dupe of #7
